### ISSUE TITLE
module 'face_recognition_models' has no attribute 'face_locations'

### ISSUE THREAD

**Issue by chaitanyajalluri** [ageitgey/face_recognition_models#6]
when i am running the below line of code :
face_recognition_models.face_locations(rgb,model="cnn")
 I am getting this error:
module 'face_recognition_models' has no attribute 'face_locations'

face_recognition_models contains same functions of face_recognition but why i am getting this error.

**Comment by maivtweb** [comment]
you can change name .py file, maybe this is duplicate name

**Comment by sasauz** [comment]
I have the same error

**Comment by ageitgey** [comment]
You are importing the wrong module. Use face_recognition not face_recognition_models.

**Comment by sasauz** [comment]
Hi Adam, thank you for your answer. 
If I'm trying to import face_recognition then I recive following error: 


'[3]: runfile('C:/Users/sasa/.spyder-py3/temp.py', wdir='C:/Users/sasa/.spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-3-83f414dfe376>", line 1, in <module>
    runfile('C:/Users/sasa/.spyder-py3/temp.py', wdir='C:/Users/sasa/.spyder-py3')

  File "C:\Programming\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Programming\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/sasa/.spyder-py3/temp.py", line 9, in <module>
    import face_recognition

ModuleNotFoundError: No module named 'face_recognition'>'

**Comment by sasauz** [comment]
This is my code:

import cv2
import face_recognition

cv2.namedWindow("preview")
vc = cv2.VideoCapture(0)

face_locations = []

if vc.isOpened(): 
&nbsp;&nbsp;&nbsp;rval, frame = vc.read()
else:
&nbsp;&nbsp;&nbsp;rval = False

while rval:
&nbsp;&nbsp;&nbsp;rval, frame = vc.read()
&nbsp;&nbsp;&nbsp;rgb_frame = frame[:, :, ::-1]
    
&nbsp;&nbsp;&nbsp;face_locations = face_recognition.face_locations(frame)
&nbsp;&nbsp;&nbsp;cv2.imshow('preview', frame)

**Comment by ageitgey** [comment]
From the import error, it seems like you haven't actually installed `face_recognition`.

**Comment by hediil** [comment]
> You are importing the wrong module. Use face_recognition not face_recognition_models.

i cant import it i find error and i dont know why help me please

**Comment by hediil** [comment]
> 

how can i import face_recignition from pycharm

**Comment by skp-1997** [comment]
Check whether you have created face_recognition.py file in your code. If yes then change the name of the file. Its interfeering with existing file of face_recognition module.

**Comment by aashishporwal1** [comment]
Try reinstalling the module
